# Naive Bayes Classifier

In [1]:
weather = [
    'Sunny',
    'Sunny',
    'Overcast',
    'Rainy',
    'Rainy',
    'Rainy',
    'Overcast',
    'Sunny',
    'Sunny',   
    'Rainy',
    'Sunny',
    'Overcast',
    'Overcast',
    'Rainy'
]

In [2]:
temp = [
    'Hot',
    'Hot',
    'Hot',
    'Mild',
    'Cool',
    'Cool',
    'Cool',
    'Mild',
    'Cool',
    'Mild',
    'Mild',
    'Mild',
    'Hot',
    'Mild'
]

In [3]:
play = [
    'No',
    'No',
    'Yes',
    'Yes',
    'Yes',
    'No',
    'Yes',
    'No',
    'Yes',
    'Yes',
    'Yes',
    'Yes',
    'Yes',
    'No'
]

In [4]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

weather_encoded=le.fit_transform(weather)

print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [6]:
temp_encoded=le.fit_transform(temp)
label = le.fit_transform(play)

print( 'temp:',temp_encoded)
print('play:',label)

temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [7]:
# COMBINING WEATHER AND TEMP INTO SINGLE LIST OF TUPLES

features = list(zip(weather_encoded, temp_encoded))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [8]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(features, label)

predicted = model.predict([[0,2]])
print("Predicted Value:", predicted)

Predicted Value: [1]


In [9]:
label_pred =model.predict(features)
label_pred

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1])

In [10]:
from sklearn import metrics

metrics.accuracy_score(label, label_pred)

0.7142857142857143

# Naive Bayes with Multiple Labels

In [11]:
from sklearn import datasets

wine = datasets.load_wine()

In [12]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [13]:
wine.data.shape

(178, 13)

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target,
                                                   test_size=0.3, random_state=109)

In [18]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

In [19]:
y_pred

array([0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 2, 2, 2, 2, 0, 1, 1, 0, 0, 1, 2, 1,
       0, 2, 0, 0, 1, 2, 0, 1, 2, 1, 1, 0, 1, 1, 0, 2, 2, 0, 2, 1, 0, 0,
       0, 2, 2, 0, 1, 1, 2, 0, 0, 2])

# decision tree classifier

In [21]:
import pandas as pd

from sklearn.tree import DecisionTreeClassifier

In [22]:
col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'predigree', 'age', 'label']
 

pima = pd.read_csv("https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/diabetes.csv", header=None, names = col_names,
                  skiprows = 1
                  )

In [23]:
pima.head()

pregnant  glucose  bp  skin  insulin   bmi  predigree  age  label
0         6      148  72    35        0  33.6      0.627   50      1
1         1       85  66    29        0  26.6      0.351   31      0
2         8      183  64     0        0  23.3      0.672   32      1
3         1       89  66    23       94  28.1      0.167   21      0
4         0      137  40    35      168  43.1      2.288   33      1

In [24]:
pima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pregnant   768 non-null    int64  
 1   glucose    768 non-null    int64  
 2   bp         768 non-null    int64  
 3   skin       768 non-null    int64  
 4   insulin    768 non-null    int64  
 5   bmi        768 non-null    float64
 6   predigree  768 non-null    float64
 7   age        768 non-null    int64  
 8   label      768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [30]:
numer = ['pregnant', 'insulin', 'bmi', 'age', 'glucose', 'bp', 'predigree', 'label']

for col in numer:
         pima[col] = pd.to_numeric(pima[col], errors='coerce')


In [31]:
pima.dropna(inplace=True)

In [32]:
feature_cols = ['pregnant', 'insulin', 'bmi', 'age', 'glucose', 'bp', 'predigree']

X = pima[feature_cols]
y = pima.label

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   test_size=0.3, random_state=1)

In [34]:
clf = DecisionTreeClassifier()

clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [35]:
# Akurasi

metrics.accuracy_score(y_test, y_pred)

0.6926406926406926

In [44]:
pip install graphviz
pip install pydotplus

SyntaxError: invalid syntax (<ipython-input-44-ec567f4eeb66>, line 1)

In [45]:
!conda install python-graphviz -y

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
                                                                                                         |failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - alabaster -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']
  - anaconda==2021.05 -> python[version='3.7.10|3.9.4|3.8.8',build='h88f2d9e_5|h88f2d9e_0']
  - appdirs -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
  - argon2-cffi -> python[version='>=2.7,

bokeh -> matplotlib -> numpy[version='>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.13.3,<2.0a0|>=1.14.6,<2.0a0|>=1.19.2,<2.0a0|>=1.20.3,<2.0a0|>=1.20.2,<2.0a0|>=1.16.6,<2.0a0|>=1.15.4,<2.0a0|>=1.9.3,<2.0a0|>=1.9.3,<1.10.0a0|>=1.9']
glue-core -> numpy[version='>=1.16|>=1.9']
bkcharts -> numpy[version='>=1.7.1']
scipy -> numpy[version='>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.6,<2.0a0|>=1.15.1,<2.0a0|>=1.9.3,<2.0a0']

Package libffi conflicts for:
toml -> python[version='>=2.7'] -> libffi[version='3.2.*|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3.0a0']
pycurl -> python[version='>=3.9,<3.10.0a0'] -> libffi[version='3.2.*|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3.0a0']
ptyprocess -> python -> libffi[version='3.2.*|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3.0a0']
ply -> python[version='>=3.9,<3.10.0a0'] -> libffi[version='3.2.*|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3.0a0']
sphinxcontrib -> python[version='>=3.9,<3.10.0a0'] -> libffi[version='3.2.*|>=3.2.1,<3.3a0|>=3.3,<3.4.0a0|>=3.2.1,<3.3.0a0']
mu

tifffile -> numpy[version='>=1.15.1'] -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1

In [47]:
!pip install pydotplus

In [48]:
import sklearn.tree as tree
import pydotplus
from sklearn.externals.six import StringIO
from IPython.display import Image

dot_data = StringIO()
tree.export_graphviz(clf,
                    out_file=dot_data,
                    class_names=['0','1'],
                    feature_names=feature_cols,
                     filled=True,
                     rounded=True,
                     special_characters=True
                    )
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

ModuleNotFoundError: No module named 'sklearn.externals.six'

# Optimizing Tree

In [49]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [50]:
metrics.accuracy_score(y_test, y_pred)

0.7705627705627706

# Random FOrest