In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x=[8.0,1,2.5,4,28.0]
x_with_nan = [8.0,1,2.5,math.nan,4,28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [6]:
#buat objek np.ndarray dan pd.series yang sesuai dengan x dan x_with.nan

y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)
print(z)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64


# Mean

In [7]:
# Mean

mean_ = sum(x)/len(x)
mean_

8.7

In [9]:
mean_ = statistics.mean(x)
print(mean_)

8.7


In [10]:
mean_=statistics.mean(x_with_nan)
print(mean_)

nan


In [11]:
mean_ = sum(x_with_nan)/len(x_with_nan)
mean_

nan

In [32]:
np.mean(y_with_nan)

nan

In [33]:
#mengabaikan nan, gunakan np.nanmean()

np.nanmean(y_with_nan)

8.7

In [35]:
mean_ = z.mean()
mean_

8.7

In [36]:
z_with_nan.mean()

8.7

# Weighted Mean

In [13]:
0.2*2+0.5*4+0.3*8

4.8

In [16]:
x=[8.0,1,2.5,4,28.0]
w=[0.1,0.2,0.3,0.25,0.15]

wmean=sum(w[i] * x[i] for i in range(len(x)))/sum(w)
print(wmean)

wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
print(wmean)

6.95
6.95


In [18]:
# untuk data yang besar, gunakan numpy

y, z, w = np.array(x),pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


In [19]:
(w*y).sum()/w.sum()

6.95

# Harmonic Mean

In [22]:
# harmonic mean bagus untuk handling outliers yang besar eg. 2,4,6,100

4/( 1/2 + 1/4 + 1/6 + 1/100)

4.316546762589928

In [23]:
hmean = len(x) / sum(1/item for item in x)
hmean

2.7613412228796843

In [24]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

In [25]:
scipy.stats.hmean(z)

2.7613412228796843

# Geometric Mean

In [49]:
# untuk mean yang menghubungkan dua variable berbeda

In [27]:
#Perbandingan arithmetic, harmonic dan geometric dari sisi hasil/output of mean
#dengan urutan dari paling kecil adalah 1. harmonic, 2. geometric, 3. arithmetic

In [28]:
gmean = 1

for item in x:
    gmean *= item
    
gmean **=1/len(x)
gmean

4.677885674856041

In [29]:
scipy.stats.gmean(y)

4.67788567485604

In [30]:
scipy.stats.gmean(z)

4.67788567485604

# Median

In [31]:
n = len(x)
if n%2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5*n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])

median_

4

In [37]:
# untuk case jumlah n genap, bisa gunakan Median_low() dan median_high()
#untuk memanggil nilai yang lebih rendah dan tinggi dari median

In [45]:
x

[8.0, 1, 2.5, 4, 28.0]

In [51]:
x[:-1]
sorted(x[:-1])

[1, 2.5, 4, 8.0]

In [40]:
statistics.median_low(x[:-1])

2.5

In [41]:
statistics.median_high(x[:-1])

4

In [58]:
# fungsi median(), median_low(), dan median_high() tidak mengembalikan nan
# ketika ada nilai nan di antara titik data

print(sorted(x_with_nan))
print(statistics.median(x_with_nan))
print(statistics.median_low(x_with_nan))
print(statistics.median_high(x_with_nan))

[1, 2.5, 4, 8.0, nan, 28.0]
6.0
4
8.0


In [60]:
print(y)
median_=np.median(y)
print(median_)

[ 8.   1.   2.5  4.  28. ]
4.0


In [61]:
median_=np.median(y[:-1])
print(median_)

3.25


# Mode

In [62]:
u = [2,3,2,8,12]

v = [12,15,12,15,21,15,12]

mode_ = max((u.count(item), item) for item in set(u)) [1]
mode_

2

In [64]:
mode_ = statistics.mode(u)
mode_

2

In [65]:
u, v = np.array(u), np.array(v)

mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [66]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

In [67]:
print(mode_.mode)
print(mode_.count)

[12]
[3]


In [74]:
# panda.Series

u, v, w = pd.Series(u), pd.Series(v), pd.Series([2,2, math.nan])

print(u.mode())

print(v.mode())

print(w.mode())

0    2
dtype: int64
0    12
1    15
dtype: int64
0    2.0
dtype: float64


In [76]:
#jika ingin tidak memperhitungan nan, cukup teruskan argumen opsional dropna = False

print(w.mode()); dropna = False

0    2.0
dtype: float64


# Measures of Variability

In [77]:
# Variance
# Stadev
# Skewness
# Percentiles
# Ranges

## Variance

In [80]:
print(x)
n = len(x)

mean_ = sum(x)/n
print(mean_)

var_ = sum((item - mean_)**2 for item in x) / (n-1)
var_

[8.0, 1, 2.5, 4, 28.0]
8.7


123.19999999999999

In [82]:
var_= statistics.variance(x)
var_

123.2

In [83]:
# fungsi numpy untuk variance
# ddof = degree of freedom

var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [84]:
var_ = y.var(ddof=1)
var_

123.19999999999999

In [85]:
#objek pd.Series memiliki metode .var() yang mengabaikan nilai nan secara default

z.var(ddof=1)

123.19999999999999

In [94]:
# jika inging perilaku yang berbeda terkait dengan nan, gunakan parameter opsional skipna

In [95]:
# dalam menghitung variance, harus aware kita hitung dari sampel atau populasi

# syntax variance untuk populasi sbb:

    # replace (n-1) with n in thepure pyhton implementation
    # use statistics.pvariance() --> ada 'p'
    # specify the parameter ddpf = 0 if using Numpy or Pandas. 
        #In Numpy, ddof can be omitted as default is 0

## Stadev

In [96]:
std_ = var_** 0.5
std_

11.099549540409285

In [97]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [98]:
np.std(y, ddof=1)

11.099549540409285

In [99]:
y.std(ddof=1)

11.099549540409285

In [106]:
z.std(ddof=1, skipna=False)

11.099549540409285

## Skewness

In [101]:
x

[8.0, 1, 2.5, 4, 28.0]

In [103]:
n = len(x)

mean_ = sum(x)/n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x)*n/((n-1)*(n-2)*std_**3))

skew_

1.9470432273905929

In [104]:
y, y_with_nan = np.array(x), np.arrray(x_with_nan)

scipy.stats.skew(y, bias=False)

AttributeError: module 'numpy' has no attribute 'arrray'

In [107]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [108]:
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

z.skew()

1.9470432273905924

In [109]:
z_with_nan.skew()

1.9470432273905924

## Percentile

In [114]:
x = [-5.0,-1.1,0.1,2.0,8.0,12.8,21.0,25.8,41.0]

In [111]:
statistics.quantiles(x, n=2)

[8.0]

In [112]:
statistics.quantiles(x, n=4, method='inclusive')

[0.1, 8.0, 21.0]

In [115]:
y=np.array(x)

np.percentile(y,5)

-3.44

In [116]:
np.percentile(y,95)

34.919999999999995

In [120]:
np.percentile(y,[25,50,75])

array([ 0.1,  8. , 21. ])

In [121]:
np.median(y)

8.0

In [128]:
np.quantile(y, 0.05)

-3.44

In [131]:
np.quantile(y, 0.95)

34.919999999999995

In [134]:
np.quantile(y,[0.25, 0.5, 0.75])

array([ 0.1,  8. , 21. ])

In [136]:
y_with_nan

# cek untuk variabel ini

array([ 8. ,  1. ,  2.5,  nan,  4. , 28. ])

In [137]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)

In [140]:
z.quantile(0.05)


-3.44

In [141]:
z.quantile(0.95)

34.919999999999995

In [142]:
z.quantile([0.25,0.5,0.75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [143]:
z_with_nan.quantile([0.25,0.5,0.75])

0.25    2.5
0.50    4.0
0.75    8.0
dtype: float64

## Range

In [124]:
np.ptp(y)


46.0

In [125]:
np.ptp(z)


27.0

In [126]:
np.ptp(y_with_nan)


nan

In [127]:
np.ptp(z_with_nan)

nan

In [144]:
np.amax(y) - np.amin(y)

46.0

In [145]:
np.nanmax(y_with_nan)-np.nanmin(y_with_nan)

27.0

In [146]:
y.max()-y.min()

46.0

In [147]:
z.max()-z.min()

46.0

In [148]:
z_with_nan.max()-z_with_nan.min()

27.0

### Interquantile Range

In [151]:
quatiles = np.quantile(y, [0.25,0.75])

In [152]:
quatiles[1]-quatiles[0]

20.9

In [153]:
quartiles = z.quantile([0.25,0.75])

In [154]:
quartiles[0.75]-quartiles[0.25]

20.9

## Summary of Desc Stats

In [155]:
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [157]:
result.nobs

9

In [158]:
result.minmax[0]


-5.0

In [159]:
result.minmax[1]

41.0

In [160]:
result.mean

11.622222222222222

In [161]:
result.variance

228.75194444444446

In [162]:
result.skewness

0.9249043136685094

In [163]:
result.kurtosis

0.14770623629658886

In [166]:
#numpy

result=z.describe()

In [165]:
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [168]:
result['mean']



11.622222222222222

In [169]:
result['std']


15.12454774346805

In [170]:
result['min']


-5.0

In [171]:
result['max']


41.0

In [172]:
result['25%']


0.1

In [173]:
result['50%']


8.0

In [174]:
result['75%']

21.0

## Correlation

In [194]:
x = list(range(-10,11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [195]:
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x), pd.Series(y)

In [196]:
x_

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [187]:
y_

array([ 0,  2,  2,  2,  3,  3,  6,  7,  4,  7,  6,  6,  9,  4,  5,  5, 10,
       11, 12, 14])

### Covariance

In [178]:
n = len(x)
mean_x, mean_y = sum(x)/n, sum(y)/n

In [183]:
cov_xy = sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n - 1)
cov_xy

19.95

In [197]:
cov_matrix = np.cov(x_, y_)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [198]:
x_.var(ddof=1)

38.5

In [200]:
y_.var(ddof=1)

13.914285714285711

In [201]:
cov_xy = cov_matrix[0,1]
cov_xy

19.950000000000003

In [202]:
cov_xy = cov_matrix[1,0]
cov_xy

19.950000000000003

In [203]:
cov_xy = x__.cov(y__)
cov_xy

19.950000000000003

In [204]:
cov_xy = y__.cov(x__)
cov_xy

19.950000000000003

In [205]:
cov_xx = x__.cov(x__)
cov_xx

38.5

In [206]:
cov_yy = y__.cov(y__)
cov_yy

13.914285714285715

### Correlation COefficient

In [207]:
var_x = sum((item - mean_x)**2 for item in x) / (n-1)
var_y = sum((item - mean_y)**2 for item in y) / (n-1)
std_x, std_y = var_x**0.5, var_y**0.5
r = cov_xy/(std_x*std_y)
r

0.861655170662956

In [211]:
r, p = scipy.stats.pearsonr(x_, y_)
r

0.8619500056316058

In [212]:
p

5.122760847201207e-07

In [213]:
corr_matrix = np.corrcoef(x_, y_)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [215]:
r = corr_matrix[0,1]
r

0.8619500056316061

In [216]:
r = corr_matrix[1,0]
r

0.8619500056316061

In [217]:
r = corr_matrix[0,0]
r

1.0

In [218]:
r = corr_matrix[1,1]
r

1.0

In [219]:
scipy.stats.linregress(x_, y_)

LinregressResult(slope=0.5181818181818182, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [220]:
result =scipy.stats.linregress(x_, y_)
r = result.rvalue
r

0.861950005631606

In [221]:
#in Pandas

r = x__.corr(y__)
r

0.8619500056316061

In [222]:
r = y__.corr(x__)
r

0.8619500056316061

###Working with 2D Data

In [228]:
a = np.array([[1,1,1],
             [2,3,1],
              [4,9,2],
              [8,27,4],
              [16,1,1]           
             ])
a

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [229]:
np.mean(a)

5.4

In [230]:
a.mean()

5.4

In [231]:
np.median(a)

2.0

In [232]:
a.var(ddof=1)

53.40000000000001

In [233]:
# menggunakan parameter opsional axis

In [234]:
# axis = None --> to calculate across all data in the array

# axis = 0 to calculate across all rows for each column

np.mean(a, axis=0)

array([6.2, 8.2, 1.8])

In [235]:
a.mean(axis=0)

array([6.2, 8.2, 1.8])

In [236]:
# axis = 1 to calculate across all columns

np.mean(a, axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [237]:
a.mean(axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [239]:
np.median(a, axis=0)

array([4., 3., 1.])

In [240]:
np.median(a, axis=1)

array([1., 2., 4., 8., 1.])

In [241]:
a.var(axis=0, ddof=1)

array([ 37.2, 121.2,   1.7])

In [242]:
a.var(axis=1, ddof=1)

array([  0.,   1.,  13., 151.,  75.])

In [244]:
scipy.stats.gmean(a)

array([4.        , 3.73719282, 1.51571657])

In [245]:
scipy.stats.gmean(a, axis=0)

array([4.        , 3.73719282, 1.51571657])

In [246]:
scipy.stats.gmean(a, axis=1)

array([1.        , 1.81712059, 4.16016765, 9.52440631, 2.5198421 ])

In [247]:
scipy.stats.gmean(a, axis=None)

2.829705017016332

In [248]:
scipy.stats.describe(a, axis=None, ddof=1, bias=False)

DescribeResult(nobs=15, minmax=(1, 27), mean=5.4, variance=53.40000000000001, skewness=2.264965290423389, kurtosis=5.212690982795767)

In [249]:
scipy.stats.describe(a, ddof=1, bias=False) # Default axis=0

DescribeResult(nobs=5, minmax=(array([1, 1, 1]), array([16, 27,  4])), mean=array([6.2, 8.2, 1.8]), variance=array([ 37.2, 121.2,   1.7]), skewness=array([1.32531471, 1.79809454, 1.71439233]), kurtosis=array([1.30376344, 3.14969121, 2.66435986]))

In [250]:
scipy.stats.describe(a, axis=1, ddof=1, bias=False)

DescribeResult(nobs=3, minmax=(array([1, 1, 2, 4, 1]), array([ 1,  3,  9, 27, 16])), mean=array([ 1.,  2.,  5., 13.,  6.]), variance=array([  0.,   1.,  13., 151.,  75.]), skewness=array([0.        , 0.        , 1.15206964, 1.52787436, 1.73205081]), kurtosis=array([-3. , -1.5, -1.5, -1.5, -1.5]))

###DataFrame

In [251]:
row_name = ['first', 'second', 'third', 'fourth', 'fifth']
col_name = ['A', 'B', 'C']
df = pd.DataFrame(a, index=row_name, columns=col_name)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [252]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [253]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [254]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [255]:
df.var(axis=1)

first       0.0
second      1.0
third      13.0
fourth    151.0
fifth      75.0
dtype: float64

In [256]:
df['A']

first      1
second     2
third      4
fourth     8
fifth     16
Name: A, dtype: int64

In [257]:
df['A'].mean()

6.2

In [258]:
df['A'].var()

37.20000000000001

In [259]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [260]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [261]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000

In [262]:
df.describe().at['mean', 'A']

6.2

In [263]:
df.describe().at['50%', 'B']

3.0

#Visualizing Data

In [285]:
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [286]:
np.random.seed(seed=0)

In [287]:
x = np.random.randn(1000)
y = np.random.randn(100)
z = np.random.randn(10)

In [289]:
#fig, ax = plt.subplots()
#ax.boxplot((x, y, z), vert=False, showmeans=True, meanline=True, labels=('x', 'y', 'z'), 
#           patch_artist=True, medianprops={'lindewidth':2, 'color':'purple'}, 
 #          meanprops={'lindewidth':2, 'color':'red'})
#plt.show()